config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/tv_shows", to: 'tv_shows#index'
  post '/tv_shows/add_to_favourites' => 'tv_shows#add_to_favourites'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
    has_many :shows
    validates :name, presence: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :channel

  validates :name, :start_time, :end_time, :channel_id, presence: true
  
  def self.search(search)
    joins(:channel).where("shows.name LIKE (?) OR channels.name LIKE (?)", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
    def index
        if params[:search]
            @tv_shows = Show.search(params[:search]).order("created_at DESC")
        else
            @tv_shows = Show.all.order('created_at DESC')
        end
    end

    def add_to_favourites
        if user_signed_in?
            # puts params[:show_id]
            # @favshow = Favourite.where('show_id= ?',params[:show_id]).where('user_id = ?',current_user.id).first
            @favshow = Favourite.where(show_id: params[:show_id],user_id: current_user.id).first
            if !@favshow 
                @favourite = Favourite.new(:show_id => params[:show_id],:user_id => current_user.id)
                if @favourite.save
                    render :json => { "message" => "Show added in favourites","success" => true }
                else
                    render :json => { "message" => "Please Try Again.","success" => false }
                end
            else
                @favshow.destroy
                render :json => { "message" => "removed","success" => false }
            end
        else
            render :json => { "message" => "login","success" => false }
        end
    end

    def remove_from_favorites
        if user_signed_in?
            # @favshow = Favourite.where('show_id = ?',params[:show_id]).where('user_id = ?',current_user.id).first
            @favshow = Favourite.where(show_id: params[:show_id],user_id: current_user.id).first
            if @favshow
                @favshow.destroy
                redirect_to "/tv_shows", status: :see_other
            end
        else
            redirect_to '/users/sign_in'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/home/index.html.erb
<div class="container m-0">
    <h1>Welcome</h1>
    <p>Your favorite TV Show reminder.</p>
    <% if user_signed_in? %>
        <p>
            <%= link_to 'Click here' , tv_shows_path %> to get a list of all shows.
        </p>
        <% else %>
            <p>
                Sign up/Login to add a show as favorite and get notification when the show is about to begin.
                <%= link_to 'Login/Signup' , new_user_registration_path %> to get a list of all shows
            </p>
            <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
  <%= link_to "TV Shows", "/", :class => 'navbar-brand'  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", "/", :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "TV Shows", "/tv_shows", :class => 'nav-link'  %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Profile", edit_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, :class => 'nav-link'  %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, :class => 'nav-link'  %>
        </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <div class="float-end">
        <%= "Welcome, #{current_user.email}" %>
      </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tv Shows</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/tv_shows/index.html.erb
<div class="container mt-5">
    <h2>TV Shows
    </h2>
    <div class="mb-3 mt-3">
        <%= form_tag(tv_shows_path, :method=> "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Shows" ,class:"form-control", required:
                true %>
                <%= submit_tag "Search" ,class:"btn btn-primaty btn-sm mt-3" %>
                    <%= link_to "Reset" , "/tv_shows" , class: "btn btn-secondary mt-3" %>
                        <% end %>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Channel</th>
                <th scope="col">Show</th>
                <th scope="col">Timing</th>
                <th scope="col">Add/ Remove Favourites</th>
            </tr>
        </thead>
        <tbody>
            <% if @tv_shows.present? %>
                <% @tv_shows.each_with_index do |show,index| %>
                    <tr>
                        <td>
                            <%= index+1 %>
                        </td>
                        <td>
                            <%= show.channel.name %>
                        </td>
                        <td>
                            <%= show.name %>
                        </td>
                        <td>
                            <%= show.start_time.strftime("%I:%M %p") + ' - ' + show.end_time.strftime("%I:%M %p") %>
                        </td>
                        <td>
                            <button class="btn btn-success btn-sm" onclick="add_to_favourites('<%= show.id %>');">
                                Favourites</button>
                        </td>
                    </tr>
                    <% end %>
                        <% else %>
                            <tr>
                                <td colspan="4" class="text-center">No shows found</td>
                            </tr>
                            <% end %>
        </tbody>
    </table>
</div>
<script>
    jQuery(document).ready(function () {
    });
    function add_to_favourites(show_id) {
        var jsondata = { 'show_id': show_id };
        jQuery.ajax({
            type: "POST",
            crossDomain: true,
            data: JSON.stringify(jsondata),
            headers: {
                'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
            },
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            url: "/tv_shows/add_to_favourites",
            success: function (data) {
                if (data.success == true) {
                    alert("Show added in favourites");
                } else if (data.success == false && data.message == 'login') {
                    window.location.href = "/users/sign_in"
                } else if (data.success == false && data.message == 'removed') {
                    alert("Show removed from favourites");
                } else if (data.success == false) {
                    alert("Please Try Again.");
                }
            },
        })
    }
</script>